name: asmarya
services:
  app:
    build: ..
    environment:
      - BACKEND_ENV=prod
    ports:
      - 8080:8080
    depends_on:
      - mysql
  mysql:
    extends:
      file: ./mysql.yml
      service: mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=4444
    ports:
      - '80:80'
    depends_on:
      - mysql
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
