# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: asmarya
services:
  mysql:
    image: mysql:8.4.0
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
    #   - ~/volumes/jhipster/asmarya/mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: '4444' # Set a password for the root user
      MYSQL_DATABASE: asmarya
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:3306:3306
    command: mysqld --lower_case_table_names=1 --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    healthcheck:
      test: ['CMD', 'mysql', '-e', 'SHOW DATABASES;']
      interval: 5s
      timeout: 5s
      retries: 10
